services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    env_file: .env
  
  glance-flask-api:
      container_name: glance-flask-api
      build:
        context: ./flask
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - 5000:5000
      env_file: .env
      volumes:
        - ./flask:/app