- name: Home
  columns:
    - size: small
      widgets:
        - type: group
          widgets:
            - type: weather
              location: ${WEATHER_LOCATION}
              units: imperial
              hour-format: 12h

            - $include: widgets/seven_day_weather.yml

            - type: calendar
              first-day-of-week: monday

        - $include: widgets/upcoming_events.yml

    - size: full
      widgets:
        # - $include: widgets/call_reminder.yml

        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true


    - size: small
      widgets:
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft

        - type: group
          widgets:
            $include: widgets/home_controls.yml
            
            $include: widgets/habit_tracker.yml